--CREATE DIFFERENT DBs for different environments

CREATE DATABASE APP_DEV_DB;
CREATE DATABASE APP_STG_DB;
CREATE DATABASE APP_PRD_DB;

--CREATE SEPERATE WAREHOUSES FOR EACH ENVIRONMENTS

CREATE WAREHOUSE APP_WH_DEV
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60;

CREATE WAREHOUSE IF NOT EXISTS APP_WH_STG
WAREHOUSE_SIZE = SMALL
AUTO_SUSPEND = 60;

CREATE WAREHOUSE IF NOT EXISTS APP_WH_PRD
WAREHOUSE_SIZE = MEDIUM
MIN_CLUSTER_COUNT = 1
MAX_CLUSTER_COUNT = 3
AUTO_SUSPEND = 60;


--CREATE ROLES
CREATE ROLE APP_DEV_ROLE;
CREATE ROLE APP_STG_ROLE;
CREATE ROLE APP_PRD_ROLE;

--CREATING ROLE HIERARCHY
GRANT ROLE APP_DEV_ROLE TO ROLE SYSADMIN;
GRANT ROLE APP_STG_ROLE TO ROLE SYSADMIN;
GRANT ROLE APP_PRD_ROLE TO ROLE SYSADMIN;

--GRANT ACCESS PERMISSIONS ON EACH ENVIRONMENTS
GRANT USAGE ON DATABASE APP_DEV_DB TO ROLE APP_DEV_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE APP_DEV_DB TO ROLE APP_DEV_ROLE;
GRANT ALL ON FUTURE TABLES IN DATABASE APP_DEV_DB TO ROLE APP_DEV_ROLE;
GRANT USAGE ON WAREHOUSE APP_WH_DEV TO ROLE APP_DEV_ROLE;

GRANT USAGE ON DATABASE APP_STG_DB TO ROLE APP_STG_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE APP_STG_DB TO ROLE APP_STG_ROLE;
GRANT ALL ON FUTURE TABLES IN DATABASE APP_STG_DB TO ROLE APP_STG_ROLE;
GRANT USAGE ON WAREHOUSE APP_WH_DEV TO ROLE APP_STG_ROLE;

GRANT USAGE ON DATABASE APP_PRD_DB TO ROLE APP_PRD_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE APP_PRD_DB TO ROLE APP_PRD_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE APP_PRD_DB TO ROLE APP_PRD_ROLE;
GRANT USAGE ON WAREHOUSE APP_WH_PRD TO ROLE APP_PRD_ROLE;

--CREATE USERS FOR EACH ENVIRONMENT

CREATE USER DEV_USER1 PASSWORD = 'DEV12AB@' DEFAULT_ROLE = DEV_ROLE DEFAULT_WAREHOUSE = APP_WH_DEV MUST_CHANGE_PASSWORD = TRUE;
GRANT ROLE APP_DEV_ROLE TO USER DEV_USER1;

CREATE USER STG_USER1 PASSWORD = 'STG12AB@' DEFAULT_ROLE = STG_ROLE DEFAULT_WAREHOUSE = APP_WH_STG MUST_CHANGE_PASSWORD = TRUE;
GRANT ROLE APP_STG_ROLE TO USER STG_USER1;

CREATE USER PRD_USER1 PASSWORD = 'PRD12AB@' DEFAULT_ROLE = PRD_ROLE DEFAULT_WAREHOUSE = APP_WH_PRD MUST_CHANGE_PASSWORD = TRUE;
GRANT ROLE APP_PRD_ROLE TO USER PRD_USER1;

SHOW GRANTS TO USER DEV_USER1;

DESCRIBE USER DEV_USER1;


